### ISSUE TITLE
Could we add user_mobile_phone to list of valid permissions?

### ISSUE THREAD

**Issue by tai-rinse** [trigger-corp/trigger.io-facebook#2]
I'm getting this error:
"You have specified one or more unknown Facebook permissions: user_mobile_phone".

It's a warning since user_mobile_phone is missing from 'permissions' list.

**Comment by antoinevg** [comment]
Facebook removed the `user_mobile_phone` permission quite some time ago.

For a list of available permissions see:

https://developers.facebook.com/docs/facebook-login/permissions
